# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\15726\Desktop\文件伪造器\forge.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_forge(object):
    def setupUi(self, forge):
        forge.setObjectName("forge")
        forge.resize(442, 261)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/img/Logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        forge.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(forge)
        self.pushButton.setGeometry(QtCore.QRect(30, 190, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(forge)
        self.label.setGeometry(QtCore.QRect(20, 20, 150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ico/img/forge.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(forge)
        self.label_2.setGeometry(QtCore.QRect(210, 60, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(forge)
        self.pushButton.clicked.connect(forge.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(forge)

    def retranslateUi(self, forge):
        _translate = QtCore.QCoreApplication.translate
        forge.setWindowTitle(_translate("forge", "伪造成功"))
        self.pushButton.setText(_translate("forge", "关闭"))
        self.label_2.setText(_translate("forge", "伪造成功"))
import rc_res
